### ISSUE TITLE
[Configuration] Start to, hide buttons, ...

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#1109]
Add configuration items:
* [x] start to view #1102
* [x] hide buttons #374
* [x] Editor/autosave on close #937
* [x] Notifications distributor interval #1104

**Comment by dvorka** [comment]
Configuration part implemented for features.
