### ISSUE TITLE
Eisenhower Matrix / Organizer @ tags

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#1359]
Improve Eisenhower Matrix so that **custom quadrants** can be defined using tags.

Hints:

* **list** of Eisenhower Matrices
    - menu/View/Eisenhower matrices <kbd>ctrl-shift-e</kbd>
    - listing table: reuse *Tags* listing    
    - Eisenhower Matrix always present (predefined/injected)
* **view** Eisenhower matrix
    - the same as before
    - *clickable* quandrant title with
      ⚙ ... https://www.compart.com/en/unicode/U+2699
      suffix
    - ^ opens configuration dialog
* **configure** Eisenhower matrix
    - dialog:
        - Eisenhower Matix name/title
        - per quadrant:
            - tag 
            - filter: o/n/o+n (drop down)
            - order by: importance/urgency (drop down)
* **menu**/Eisenhower (copy/paste Notebook actions)
    - New
    - Edit
    - Deprecate
    - ...
    - clone
- **full keyboard navigation**
    - use tab to jump between quadrant or other shortcut
    - <kbd>Alt-LEFT</kbd> or <kbd>Alt-RIGHT</kbd>
      (1-2-3-4-1... quadrants rotation)
* **backend** option A:
    - `$MF-REPO/mind/organizer`
        - name.md
```
# name
* tag-for-quadrant-1
* tag-for-quadrant-2
* tag-for-quadrant-3
* tag-for-quadrant-4
Sort by: importance / urgency
Filter: outlines / notes / outlines+notes
```
* **backend** option B:
    - `$MF-REPO/mind/organizers.md`
```
# Organizers

# Organizer Name A
* tag-for-quadrant-1
* tag-for-quadrant-2
* tag-for-quadrant-3
* tag-for-quadrant-4
Sort by: importance / urgency
Filter: outlines / notes / outlines+notes

# Organizer Name B
* tag-for-quadrant-1
* tag-for-quadrant-2
* tag-for-quadrant-3
* tag-for-quadrant-4
Sort by: importance / urgency
Filter: outlines / notes / outlines+notes
```
* parsed using O parser, loaded using `Organizer.fromOutline()`

**Comment by dvorka** [comment]
**Tasks:**

* [ ] remove dead end code:
```
	app/src/qt/dialogs/organizer_cfg_dialog.cpp
	app/src/qt/dialogs/organizer_cfg_dialog.h
```
* [x]  remove menu/Preferences/Eisenhower Matrices
* [x] organizer @ outlines
* [ ] edit organizer
* [ ] clone organizer
* [ ] delete organizer
* [x] set quadrant titles (name OR list of tags)
* [ ] add organizer scope (O chooser)
    - [ ] check O validity on *list of organizers* load in UI (if O invalid, remove organizer from config)
* [ ] reorder organizers based on which was used last ~ recently opened ~ at the top of the page
* [ ] organizer @ notes
    - [ ] change available tags from outline tags to note tags (if there is something like that)
* [ ] organizer @ outlines + notes
    - [ ] list of entities may contain O or N
    - [ ] N's method to self filter
    - [ ] UI click can distinguish O / N and open it (recent view)
    - [ ] N name w/ O name as suffix in the listing
    - [ ] sort quadrant entries by Name (recently opened timestamp! *better*) 
* [ ] drag & drop explainers removes / adds tags
* [ ] if notebook scope is set, verify whether notebook exists on explainers list load to table (UI) and if not, discard organizer
* [ ] organizer view
   * [ ] show organizer name atop quadrants
   * [ ] show O or/and N tags
* [ ] non-quoted (,,) rendering of tags in quadrant title (set serialization hint)
* [ ] organizer quadrant tags deduplication: from vector to set
* [ ] bug: update organizer > Ns duplicated after clicking `Update` button
* [ ] bug: edit organizer > remove tags > no change ~ tags stay the same

**Comment by dvorka** [comment]
![em](https://user-images.githubusercontent.com/2090143/139556571-ccc46d2a-95ea-45ee-9ba3-2561406a3e24.png)

@stexyz FYI Eisenhower Matrix on tags is on the way and will be released with 1.53.0
