### ISSUE TITLE
Release CHECKLIST

### ISSUE THREAD

**Issue by dvorka** [dvorka/mindforger#411]
Release checklist:
1. [ ] BB to GH - `mindforger-repository` (initial repository is a part of distribution)
1. [ ] source version.h 0.42.0
1. [ ] tag and branch 0.42.0
1. [ ] Launchpad release (script)
1. [ ] build `.deb` (script)
1. [ ] tarball `.tar.gz` (created by .deb script)
1. [ ] build `.rpm` (script @ Fedora VM)
1. [ ] test clean installation of MF w/ empty home directory (mf-repo to be copied to home if ! exist)
1. [ ] GH `mindforger` repository - index.md to readme.md (check links)
1. [ ] GH `mindforger` repository - release 0.42.0 + upload of .deb/.rpm/.tarball
1. [ ] web `test` to `www` (check links)
1. [ ] FB cover image
1. [ ] FB announcement
1. [ ] Twitter announcement
1. [ ] SF web (copy of mf.com)
1. [ ] SF announcement
1. [ ] YouTube to be planned
1. [ ] GAnalytics check
